import { createHash } from "crypto";
import { prisma } from "../prisma";
import { blobStore } from "../blob-store";
import { writeAuditLog } from "../audit";
import type { NormalizedMessage } from "../graph/message-types";
import { isAutoReply } from "./auto-reply";
import { classifyPriority } from "./priority";
import { matchSuppressionRule } from "./suppression";
import { extractTicketNoFromSubject } from "./subject-ticket-match";
import { validateAttachment } from "./attachments";
import { createTicket } from "../tickets/create-ticket";
import { writeStatusHistory } from "../tickets/history";
import { autoResponseReceivedFor } from "../tickets/auto-response";
import { sendAcknowledgementEmail, shouldSendAcknowledgement } from "../email/acknowledgement";
import { HR_MAILBOX_ADDRESS } from "../email/send";

// A real actor is required for audit_log/ticket_notes rows generated by
// automated ingestion (both are non-nullable FKs to users) -- the spec
// never names one, so this is seeded explicitly (prisma/seed.ts) rather
// than invented ad hoc here. Filtered out of user-facing pickers
// (app/api/users/route.ts) by this same sentinel entraObjectId.
export const SYSTEM_ENTRA_OBJECT_ID = "system";

let systemUserId: string | null = null;
/** Exported for Stage 5's sla-escalation job, which is the other automated actor needing this same seeded system user. */
export async function getSystemUserId(): Promise<string> {
  if (systemUserId) return systemUserId;
  const user = await prisma.user.findUnique({ where: { entraObjectId: SYSTEM_ENTRA_OBJECT_ID } });
  if (!user) throw new Error('System user not seeded -- run "prisma db seed" (see prisma/seed.ts)');
  systemUserId = user.id;
  return systemUserId;
}

async function storeAttachments(
  message: NormalizedMessage,
  ticketId: string,
  messageId: string,
  correlationId: string,
): Promise<void> {
  for (const att of message.attachments) {
    const validation = validateAttachment(att);

    // SKIPPED (§7.3.1's "inline images under 10KB. Ignored") means exactly
    // that -- ignored, not stored-but-hidden. Found 2026-09-23: this loop
    // used to store and create a ticket_attachments row for these anyway
    // (just labelled SKIPPED), so every email signature/footer logo still
    // cluttered the ticket's attachments panel. "Nothing is silently lost"
    // (the reason BLOCKED attachments *are* still stored) doesn't apply
    // here -- a decorative inline image was never something a human
    // attached in the first place, there's nothing of substance to lose.
    if (validation.scanStatus === "SKIPPED") continue;

    const sha256 = createHash("sha256").update(att.content).digest("hex");
    // Stored regardless of outcome -- "nothing is silently lost" (§7.3.1)
    // applies to blocked attachments too; scan_status/download-ability
    // (Stage 7) is what actually gates access, not storage itself.
    const blobPath = `attachments/${ticketId}/${messageId}/${att.filename}`;
    await blobStore.save(blobPath, att.content);

    const record = await prisma.ticketAttachment.create({
      data: {
        ticketId,
        messageId,
        filename: att.filename,
        declaredContentType: att.declaredContentType,
        detectedContentType: validation.detectedContentType,
        sizeBytes: att.sizeBytes,
        blobPath,
        sha256,
        source: "EMAIL",
        scanStatus: validation.scanStatus,
        blockReason: validation.blockReason,
      },
    });

    if (validation.scanStatus === "BLOCKED") {
      const systemId = await getSystemUserId();
      await prisma.ticketNote.create({
        data: {
          ticketId,
          authorId: systemId,
          body: `Attachment "${att.filename}" was blocked (${validation.blockReason}) and is not available on this ticket.`,
        },
      });
      await writeAuditLog({
        correlationId,
        actorId: systemId,
        action: "ATTACHMENT_BLOCKED",
        entity: "ticket_attachment",
        entityId: record.id,
        ticketId,
        afterJson: { filename: att.filename, blockReason: validation.blockReason },
      });
    }
  }
}

export type ProcessMessageOutcome =
  | { action: "DUPLICATE"; ticketId: string }
  | { action: "SUPPRESSED"; ruleId: string }
  | { action: "AUTO_REPLY_IGNORED" }
  | { action: "THREADED"; ticketId: string; messageId: string }
  | { action: "CREATED"; ticketId: string; ticketNo: string };

/**
 * §7.3, evaluated in the exact order the spec gives: suppression, then
 * auto-reply, then threading, then create. The one function every real
 * entry point (webhook, delta poller, and for now the dev-only fixture
 * endpoint) calls -- Graph-agnostic by design, see lib/graph/message-types.ts.
 */
export async function processInboundMessage(
  message: NormalizedMessage,
  correlationId: string,
): Promise<ProcessMessageOutcome> {
  // Idempotency (§7.2, and §15's own "duplicate delivery creates exactly
  // one ticket" acceptance test): checked explicitly so a duplicate is a
  // clear, named outcome rather than a caught constraint-violation error.
  const existingMessage = await prisma.ticketMessage.findUnique({
    where: { internetMessageId: message.internetMessageId },
  });
  if (existingMessage) {
    return { action: "DUPLICATE", ticketId: existingMessage.ticketId };
  }

  const rules = await prisma.suppressionRule.findMany({ where: { isActive: true } });
  const matchedRule = matchSuppressionRule(message, rules);
  if (matchedRule) {
    await prisma.suppressionLog.create({
      data: {
        ruleId: matchedRule.id,
        fromAddress: message.fromAddress,
        subject: message.subject,
        internetMessageId: message.internetMessageId,
        receivedAt: message.receivedAt,
        correlationId,
      },
    });
    return { action: "SUPPRESSED", ruleId: matchedRule.id };
  }

  if (isAutoReply(message.internetMessageHeaders)) {
    return { action: "AUTO_REPLY_IGNORED" };
  }

  // §7.3 step 3: threading -- conversation_id lives on ticket_messages, so
  // matching "an existing non-archived ticket" means matching through its messages.
  let existingTicket = await prisma.ticket.findFirst({
    where: {
      messages: { some: { conversationId: message.conversationId } },
      status: { not: "ARCHIVED" },
    },
  });

  // Operator addition (not in v1.3 spec): fallback when conversation_id
  // threading finds nothing -- a reply whose subject still carries the
  // ticket number (every outbound email puts it there, see
  // lib/email/templates.ts) still threads onto the right ticket even if
  // it arrived as a fresh email or lost its threading headers along the
  // way. Matches on subject alone, no sender/requester check -- an
  // explicit operator decision (asked, not guessed), see STATUS.md.
  if (!existingTicket) {
    const ticketNo = extractTicketNoFromSubject(message.subject);
    if (ticketNo) {
      existingTicket = await prisma.ticket.findFirst({
        where: { ticketNo, status: { not: "ARCHIVED" } },
      });
    }
  }

  if (existingTicket) {
    const reply = await prisma.ticketMessage.create({
      data: {
        ticketId: existingTicket.id,
        direction: "INBOUND",
        messageType: "REPLY",
        graphMessageId: message.graphMessageId,
        internetMessageId: message.internetMessageId,
        conversationId: message.conversationId,
        fromAddress: message.fromAddress,
        fromName: message.fromName,
        toRecipients: message.toRecipients,
        ccRecipients: message.ccRecipients,
        subject: message.subject,
        bodyHtml: message.bodyHtml,
        bodyText: message.bodyText,
        receivedAt: message.receivedAt,
        correlationId,
      },
    });
    await storeAttachments(message, existingTicket.id, reply.id, correlationId);
    await markResponseReceived(existingTicket, message, correlationId);
    return { action: "THREADED", ticketId: existingTicket.id, messageId: reply.id };
  }

  // §7.3 step 4: create.
  const priority = classifyPriority(message.subject);
  const created = await createTicket({
    receivedAt: message.receivedAt,
    subject: message.subject,
    requesterEmail: message.fromAddress,
    requesterName: message.fromName || message.fromAddress,
    priority,
    firstMessage: {
      direction: "INBOUND",
      messageType: "ORIGINAL",
      graphMessageId: message.graphMessageId,
      internetMessageId: message.internetMessageId,
      conversationId: message.conversationId,
      fromAddress: message.fromAddress,
      fromName: message.fromName,
      toRecipients: message.toRecipients,
      ccRecipients: message.ccRecipients,
      bodyHtml: message.bodyHtml,
      bodyText: message.bodyText,
      correlationId,
    },
  });

  await storeAttachments(message, created.ticketId, created.firstMessageId, correlationId);

  await writeAuditLog({
    correlationId,
    actorId: await getSystemUserId(),
    action: "TICKET_CREATED",
    entity: "ticket",
    entityId: created.ticketId,
    ticketId: created.ticketId,
    afterJson: { ticketNo: created.ticketNo, priority, requesterEmail: message.fromAddress },
  });

  // Operator amendment (John, 2026-10-03): acknowledge on creation, not on
  // allocation. Recent mail only -- see shouldSendAcknowledgement().
  const requesterEmail = message.fromAddress;
  if (shouldSendAcknowledgement({ receivedAt: message.receivedAt, requesterEmail })) {
    await sendAcknowledgementEmail(
      { id: created.ticketId, ticketNo: created.ticketNo, subject: message.subject || "(no subject)", requesterEmail },
      correlationId,
      await getSystemUserId(),
    );
  }

  return { action: "CREATED", ticketId: created.ticketId, ticketNo: created.ticketNo };
}

/**
 * Operator amendment (John, 2026-10-03): an emailed reply on an assigned
 * ticket that is being worked moves it to RESPONSE_RECEIVED automatically
 * and raises the assignee's in-app alert -- the same thing staff do by hand
 * from the Current action dropdown. Rules are in lib/tickets/auto-response.ts.
 */
async function markResponseReceived(
  ticket: { id: string; status: string; assignedToId: string | null },
  message: NormalizedMessage,
  correlationId: string,
): Promise<void> {
  const decision = autoResponseReceivedFor(ticket, message.fromAddress, HR_MAILBOX_ADDRESS);
  if (decision === "NONE") return;

  const systemId = await getSystemUserId();
  const from = message.fromName ? `${message.fromName} (${message.fromAddress})` : message.fromAddress;

  if (decision === "ALERT_ONLY") {
    await prisma.ticket.update({ where: { id: ticket.id }, data: { responseAlertPending: true } });
    return;
  }

  // Conditional on the status read a moment ago, so a staff change made in
  // between wins rather than being overwritten.
  const result = await prisma.ticket.updateMany({
    where: { id: ticket.id, status: ticket.status as "IN_ACTION" | "AWAITING_RESPONSE" },
    data: { status: "RESPONSE_RECEIVED", responseAlertPending: true, version: { increment: 1 } },
  });
  if (result.count === 0) return;

  await writeStatusHistory({
    ticketId: ticket.id,
    fromStatus: ticket.status as "IN_ACTION" | "AWAITING_RESPONSE",
    toStatus: "RESPONSE_RECEIVED",
    actorId: systemId,
    reason: `Email reply received from ${from}`,
    correlationId,
  });
  await writeAuditLog({
    correlationId,
    actorId: systemId,
    action: "TICKET_STATUS_CHANGED",
    entity: "ticket",
    entityId: ticket.id,
    ticketId: ticket.id,
    beforeJson: { status: ticket.status },
    afterJson: { status: "RESPONSE_RECEIVED", responseAlertPending: true, trigger: "EMAIL_REPLY", from: message.fromAddress },
  });
}
