import { createHash } from "crypto";
import { Prisma } from "@prisma/client";
import { prisma } from "../prisma";
import { blobStore } from "../blob-store";
import { writeAuditLog } from "../audit";
import { melbourneDateOnly } from "../timezone";
import type { NormalizedMessage } from "../graph/message-types";
import { isAutoReply } from "./auto-reply";
import { classifyPriority } from "./priority";
import { matchSuppressionRule } from "./suppression";
import { ticketNoWithSequence } from "./ticket-number";
import { extractTicketNoFromSubject } from "./subject-ticket-match";
import { validateAttachment } from "./attachments";
import { SLA_HOURS } from "../tickets/sla";

// A real actor is required for audit_log/ticket_notes rows generated by
// automated ingestion (both are non-nullable FKs to users) -- the spec
// never names one, so this is seeded explicitly (prisma/seed.ts) rather
// than invented ad hoc here. Filtered out of user-facing pickers
// (app/api/users/route.ts) by this same sentinel entraObjectId.
export const SYSTEM_ENTRA_OBJECT_ID = "system";

let systemUserId: string | null = null;
/** Exported for Stage 5's sla-escalation job, which is the other automated actor needing this same seeded system user. */
export async function getSystemUserId(): Promise<string> {
  if (systemUserId) return systemUserId;
  const user = await prisma.user.findUnique({ where: { entraObjectId: SYSTEM_ENTRA_OBJECT_ID } });
  if (!user) throw new Error('System user not seeded -- run "prisma db seed" (see prisma/seed.ts)');
  systemUserId = user.id;
  return systemUserId;
}

function isTicketNoCollision(err: unknown): boolean {
  return (
    err instanceof Prisma.PrismaClientKnownRequestError &&
    err.code === "P2002" &&
    Array.isArray((err.meta as { target?: unknown })?.target) &&
    ((err.meta as { target: string[] }).target).some((t) => t.includes("ticket_no"))
  );
}

async function storeAttachments(
  message: NormalizedMessage,
  ticketId: string,
  messageId: string,
  correlationId: string,
): Promise<void> {
  for (const att of message.attachments) {
    const validation = validateAttachment(att);
    const sha256 = createHash("sha256").update(att.content).digest("hex");
    // Stored regardless of outcome -- "nothing is silently lost" (§7.3.1)
    // applies to blocked attachments too; scan_status/download-ability
    // (Stage 7) is what actually gates access, not storage itself.
    const blobPath = `attachments/${ticketId}/${messageId}/${att.filename}`;
    await blobStore.save(blobPath, att.content);

    const record = await prisma.ticketAttachment.create({
      data: {
        ticketId,
        messageId,
        filename: att.filename,
        declaredContentType: att.declaredContentType,
        detectedContentType: validation.detectedContentType,
        sizeBytes: att.sizeBytes,
        blobPath,
        sha256,
        source: "EMAIL",
        scanStatus: validation.scanStatus,
        blockReason: validation.blockReason,
      },
    });

    if (validation.scanStatus === "BLOCKED") {
      const systemId = await getSystemUserId();
      await prisma.ticketNote.create({
        data: {
          ticketId,
          authorId: systemId,
          body: `Attachment "${att.filename}" was blocked (${validation.blockReason}) and is not available on this ticket.`,
        },
      });
      await writeAuditLog({
        correlationId,
        actorId: systemId,
        action: "ATTACHMENT_BLOCKED",
        entity: "ticket_attachment",
        entityId: record.id,
        ticketId,
        afterJson: { filename: att.filename, blockReason: validation.blockReason },
      });
    }
  }
}

export type ProcessMessageOutcome =
  | { action: "DUPLICATE"; ticketId: string }
  | { action: "SUPPRESSED"; ruleId: string }
  | { action: "AUTO_REPLY_IGNORED" }
  | { action: "THREADED"; ticketId: string; messageId: string }
  | { action: "CREATED"; ticketId: string; ticketNo: string };

/**
 * §7.3, evaluated in the exact order the spec gives: suppression, then
 * auto-reply, then threading, then create. The one function every real
 * entry point (webhook, delta poller, and for now the dev-only fixture
 * endpoint) calls -- Graph-agnostic by design, see lib/graph/message-types.ts.
 */
export async function processInboundMessage(
  message: NormalizedMessage,
  correlationId: string,
): Promise<ProcessMessageOutcome> {
  // Idempotency (§7.2, and §15's own "duplicate delivery creates exactly
  // one ticket" acceptance test): checked explicitly so a duplicate is a
  // clear, named outcome rather than a caught constraint-violation error.
  const existingMessage = await prisma.ticketMessage.findUnique({
    where: { internetMessageId: message.internetMessageId },
  });
  if (existingMessage) {
    return { action: "DUPLICATE", ticketId: existingMessage.ticketId };
  }

  const rules = await prisma.suppressionRule.findMany({ where: { isActive: true } });
  const matchedRule = matchSuppressionRule(message, rules);
  if (matchedRule) {
    await prisma.suppressionLog.create({
      data: {
        ruleId: matchedRule.id,
        fromAddress: message.fromAddress,
        subject: message.subject,
        internetMessageId: message.internetMessageId,
        receivedAt: message.receivedAt,
        correlationId,
      },
    });
    return { action: "SUPPRESSED", ruleId: matchedRule.id };
  }

  if (isAutoReply(message.internetMessageHeaders)) {
    return { action: "AUTO_REPLY_IGNORED" };
  }

  // §7.3 step 3: threading -- conversation_id lives on ticket_messages, so
  // matching "an existing non-archived ticket" means matching through its messages.
  let existingTicket = await prisma.ticket.findFirst({
    where: {
      messages: { some: { conversationId: message.conversationId } },
      status: { not: "ARCHIVED" },
    },
  });

  // Operator addition (not in v1.3 spec): fallback when conversation_id
  // threading finds nothing -- a reply whose subject still carries the
  // ticket number (every outbound email puts it there, see
  // lib/email/templates.ts) still threads onto the right ticket even if
  // it arrived as a fresh email or lost its threading headers along the
  // way. Matches on subject alone, no sender/requester check -- an
  // explicit operator decision (asked, not guessed), see STATUS.md.
  if (!existingTicket) {
    const ticketNo = extractTicketNoFromSubject(message.subject);
    if (ticketNo) {
      existingTicket = await prisma.ticket.findFirst({
        where: { ticketNo, status: { not: "ARCHIVED" } },
      });
    }
  }

  if (existingTicket) {
    const reply = await prisma.ticketMessage.create({
      data: {
        ticketId: existingTicket.id,
        direction: "INBOUND",
        messageType: "REPLY",
        graphMessageId: message.graphMessageId,
        internetMessageId: message.internetMessageId,
        conversationId: message.conversationId,
        fromAddress: message.fromAddress,
        fromName: message.fromName,
        toRecipients: message.toRecipients,
        ccRecipients: message.ccRecipients,
        subject: message.subject,
        bodyHtml: message.bodyHtml,
        bodyText: message.bodyText,
        receivedAt: message.receivedAt,
        correlationId,
      },
    });
    await storeAttachments(message, existingTicket.id, reply.id, correlationId);
    // §4's "notifies the new assignee internally" (for reassignment) has no
    // channel yet (Stage 5) -- a reply's internal notification to the
    // current assignee is the same kind of gap, deferred for the same reason.
    return { action: "THREADED", ticketId: existingTicket.id, messageId: reply.id };
  }

  // §7.3 step 4: create.
  const priority = classifyPriority(message.subject);
  const slaDueAt = new Date(message.receivedAt.getTime() + SLA_HOURS[priority] * 60 * 60 * 1000);
  const requestDate = melbourneDateOnly(message.receivedAt);
  const retentionPurgeDate = new Date(requestDate);
  retentionPurgeDate.setUTCFullYear(retentionPurgeDate.getUTCFullYear() + 7);
  const subject = message.subject || "(no subject)";

  const MAX_SEQUENCE = 99; // varchar(12) = 10-digit base + 2-digit sequence
  for (let sequence = 1; sequence <= MAX_SEQUENCE; sequence++) {
    const ticketNo = ticketNoWithSequence(message.receivedAt, sequence);
    try {
      const ticket = await prisma.ticket.create({
        data: {
          ticketNo,
          originalSubject: subject,
          subject,
          requesterEmail: message.fromAddress,
          requesterName: message.fromName || message.fromAddress,
          ccRecipients: [],
          receivedAt: message.receivedAt,
          requestDate,
          priority,
          slaDueAt,
          status: "NEW",
          retentionPurgeDate,
          messages: {
            create: {
              direction: "INBOUND",
              messageType: "ORIGINAL",
              graphMessageId: message.graphMessageId,
              internetMessageId: message.internetMessageId,
              conversationId: message.conversationId,
              fromAddress: message.fromAddress,
              fromName: message.fromName,
              toRecipients: message.toRecipients,
              ccRecipients: message.ccRecipients,
              subject,
              bodyHtml: message.bodyHtml,
              bodyText: message.bodyText,
              receivedAt: message.receivedAt,
              correlationId,
            },
          },
        },
        include: { messages: true },
      });

      await storeAttachments(message, ticket.id, ticket.messages[0].id, correlationId);

      await writeAuditLog({
        correlationId,
        actorId: await getSystemUserId(),
        action: "TICKET_CREATED",
        entity: "ticket",
        entityId: ticket.id,
        ticketId: ticket.id,
        afterJson: { ticketNo, priority, requesterEmail: message.fromAddress },
      });

      return { action: "CREATED", ticketId: ticket.id, ticketNo };
    } catch (err) {
      if (isTicketNoCollision(err)) continue;
      throw err;
    }
  }

  throw new Error(`Exhausted ${MAX_SEQUENCE} ticket_no sequence values for the same minute -- should never happen in practice`);
}
